### PR TITLE
Different message for RO's

### PR DESCRIPTION
**Pull request by Fortunate-MAN**
[Me and Nobody](http://chat.stackoverflow.com/transcript/message/35731247#35731247) discussed that it would be better if RO's would be shown a different message when they run the `privileges` command instead of saying that "you do not have any privileges" as RO's can run any command without privileges. 

As some parts of code of FireAlarm are in SwiftChatSE, I had to make the change here. **Please review the change before merging as I am not familiar with Swift.**

### CODE REVIEW

**Comment by Fortunate-MAN** [comment]
uh yeah. That's my mistake; fixing it now.

**Comment by Fortunate-MAN** [comment]
Just made a commit to fix https://github.com/SOBotics/FireAlarm/issues/5

**Comment by Fortunate-MAN** [comment]
@NobodyNada change "SockFireAlarm" to "FireAlarm" now. Is it okay now?

**Comment by NobodyNada** [comment]
@Fortunate-MAN Yep!  I've gone ahead and changed the punctuation code as well.

**Pull request merged**
